[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "server how to"
authors = [{name = "Matej", email = "matej.uhrin@cvut.cz"}]
dynamic = ["version", "description"]
